######################################################################
#
# File name : bufferTB_wave.do
# Created on: Tue Jul 09 09:46:15 -0500 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
