######################################################################
#
# File name : bufferTB_simulate.do
# Created on: Wed Jul 10 10:22:45 -0500 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -L xpm -lib xil_defaultlib xil_defaultlib.bufferTB xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {bufferTB_wave.do}

view wave
view structure
view signals

do {bufferTB.udo}

run 1000ns
