######################################################################
#
# File name : bufferTB_compile.do
# Created on: Wed Jul 10 10:22:41 -0500 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/work
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlib modelsim_lib/msim/xil_defaultlib

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -64 -incr -work xil_defaultlib  "+incdir+../../../../ADC_Test.srcs/sources_1/bd/ADC_Control/ipshared/ec67/hdl" "+incdir+../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
"../../../../ADC_Test.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_sim_netlist.v" \
"../../../../ADC_Test.srcs/sources_1/ip/adc_fifo/adc_fifo_sim_netlist.v" \
"../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_sim_netlist.v" \
"../../../../rtl/eth/axis_async_fifo.v" \
"../../../../rtl/eth/axis_gmii_rx.v" \
"../../../../rtl/eth/axis_gmii_tx.v" \
"../../../../rtl/eth/eth_axis_rx.v" \
"../../../../rtl/eth/eth_axis_tx.v" \
"../../../../rtl/eth/eth_mac_1g.v" \
"../../../../rtl/eth/eth_mac_1g_rgmii.v" \
"../../../../rtl/eth/eth_mac_1g_rgmii_fifo.v" \
"../../../../rtl/eth/iddr.v" \
"../../../../rtl/eth/ip_eth_rx.v" \
"../../../../rtl/eth/ip_eth_tx.v" \
"../../../../rtl/eth/lfsr.v" \
"../../../../rtl/eth/oddr.v" \
"../../../../rtl/eth/rgmii_phy_if.v" \
"../../../../rtl/eth/ssio_ddr_in.v" \
"../../../../rtl/eth/udp_ip_rx.v" \
"../../../../rtl/eth/udp_ip_tx.v" \

C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -64 -incr -sv -work xil_defaultlib  "+incdir+../../../../ADC_Test.srcs/sources_1/bd/ADC_Control/ipshared/ec67/hdl" "+incdir+../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
"../../../../rtl/adc_cdc.sv" \
"../../../../rtl/eth/eth.sv" \
"../../../../rtl/readController.sv" \
"../../../../rtl/rstBridge.sv" \
"../../../../rtl/eth/udp_rx.sv" \
"../../../../rtl/eth/udp_tx.sv" \
"../../../../rtl/widthConverter.sv" \
"../../../../rtl/writeController.sv" \
"../../../../sim/bufferTB.sv" \

# compile glbl module
C:\\Modeltech_pe_edu_10.4a\\win32pe_edu\\vlog -work xil_defaultlib "glbl.v"

quit -force

