######################################################################
#
# File name : bufferTB_compile.do
# Created on: Thu Jul 11 12:58:04 -0500 2019
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
transcript off
onbreak {quit}
onerror {quit}

transcript on
vlib work


vlib activehdl/xil_defaultlib
vdel -lib xil_defaultlib -all
vlib activehdl/fifo_generator_v13_2_4
vdel -lib fifo_generator_v13_2_4 -all

null [set origin_dir "C:/Users/xtjac/Documents/ADC_Test/ADC_Test.sim/sim_1/behav/activehdl"]
null [set vlog_opts {-dbg -l xpm -l xil_defaultlib -l fifo_generator_v13_2_4}]
null [set vcom_opts {-dbg}]


vlog -sv2k12 {*}$vlog_opts -work xil_defaultlib  "+incdir+$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
	"$origin_dir/../../../../../../../../Xilinx/Vivado/2019.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
	"$origin_dir/../../../../../../../../Xilinx/Vivado/2019.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \

vlog -v2k5 {*}$vlog_opts -work fifo_generator_v13_2_4  "+incdir+$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/fifo_generator_0/simulation/fifo_generator_vlog_beh.v" \

vcom -93 {*}$vcom_opts -work fifo_generator_v13_2_4  \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.vhd" \

vlog -v2k5 {*}$vlog_opts -work fifo_generator_v13_2_4  "+incdir+$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/fifo_generator_0/hdl/fifo_generator_v13_2_rfs.v" \

vlog -v2k5 {*}$vlog_opts -work xil_defaultlib  "+incdir+$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/fifo_generator_0/sim/fifo_generator_0.v" \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/adc_fifo/sim/adc_fifo.v" \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_clk_wiz.v" \
	"$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.v" \
	"$origin_dir/../../../../rtl/eth/axis_async_fifo.v" \
	"$origin_dir/../../../../rtl/eth/axis_gmii_rx.v" \
	"$origin_dir/../../../../rtl/eth/axis_gmii_tx.v" \
	"$origin_dir/../../../../rtl/eth/eth_axis_rx.v" \
	"$origin_dir/../../../../rtl/eth/eth_axis_tx.v" \
	"$origin_dir/../../../../rtl/eth/eth_mac_1g.v" \
	"$origin_dir/../../../../rtl/eth/eth_mac_1g_rgmii.v" \
	"$origin_dir/../../../../rtl/eth/eth_mac_1g_rgmii_fifo.v" \
	"$origin_dir/../../../../rtl/eth/iddr.v" \
	"$origin_dir/../../../../rtl/eth/ip_eth_rx.v" \
	"$origin_dir/../../../../rtl/eth/ip_eth_tx.v" \
	"$origin_dir/../../../../rtl/eth/lfsr.v" \
	"$origin_dir/../../../../rtl/eth/oddr.v" \
	"$origin_dir/../../../../rtl/eth/rgmii_phy_if.v" \
	"$origin_dir/../../../../rtl/eth/ssio_ddr_in.v" \
	"$origin_dir/../../../../rtl/eth/udp_ip_rx.v" \
	"$origin_dir/../../../../rtl/eth/udp_ip_tx.v" \

vlog -sv2k12 {*}$vlog_opts -work xil_defaultlib  "+incdir+$origin_dir/../../../../ADC_Test.srcs/sources_1/ip/clk_wiz_0" \
	"$origin_dir/../../../../rtl/adc_cdc.sv" \
	"$origin_dir/../../../../rtl/eth/eth.sv" \
	"$origin_dir/../../../../rtl/readController.sv" \
	"$origin_dir/../../../../rtl/rstBridge.sv" \
	"$origin_dir/../../../../rtl/eth/udp_rx.sv" \
	"$origin_dir/../../../../rtl/eth/udp_tx.sv" \
	"$origin_dir/../../../../rtl/widthConverter.sv" \
	"$origin_dir/../../../../rtl/writeController.sv" \
	"$origin_dir/../../../../sim/bufferTB.sv" \


# compile glbl module
vlog -work xil_defaultlib "C:/Users/xtjac/Documents/ADC_Test/ADC_Test.sim/sim_1/behav/activehdl/glbl.v"

quit
